### get all users
GET http://localhost:3000/auth/users

### get user by id
GET http://localhost:3000/auth/2


### get user by email
GET http://localhost:3000/auth?email=1111@gmail.com

### update user
PATCH http://localhost:3000/auth/4
content-type: application/json

{
    "email": "5@gmail.com"
}

### delete user
DELETE http://localhost:3000/auth/321312

